name: sautifyv2
description: "A new Flutter project."

publish_to: "none"

version: 0.0.42

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  just_audio_background: any
  just_audio: any
  provider: any
  shared_preferences: any
  http: any
  dio: any
  dio_smart_retry: any
  audio_service: any
  audio_session: any
  dart_ytmusic_api: any
  skeletonizer: any
  mini_music_visualizer: any
  # flutter_audio_output: ^0.0.4
  #youtube_explode_dart_plus: ^1.0.3
  # logger: ^2.6.1
  youtube_explode_dart: any
  permission_handler: any
  on_audio_query: any
  file_picker: any
  hive: any
  hive_flutter: any
  flutter_native_splash: any
  #just_audio_media_kit: ^2.1.0
  #just_audio_windows: ^0.2.2
  #just_audio_libwinmedia: ^0.0.4+1
  # Replaced palette_generator with material_color_utilities for lighter, faster palette extraction
  material_color_utilities: any
  connectivity_plus: any
  path_provider: any
  package_info_plus: any
  url_launcher: any
  expressive_refresh: any
  material_new_shapes: any
  flutter_m3shapes: any
  expressive_loading_indicator: any
  flutter_animate: any
  progress_indicator_m3e: any
  navigation_bar_m3e: any
  loading_indicator_m3e: any
  m3e_design: any
  marquee: any
  rxdart: any
  just_audio_cache: any
  google_fonts: ^6.3.3

dependency_overrides:
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: any

flutter:
  uses-material-design: true
  generate: true

icons_launcher:
  image_path: "assets/icons/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter_native_splash:
  color: "#0c0b0b"

  image: assets/icons/sautify.png

  android_12:
    color: "#101011"
